-// uiDatePicker 
-
-self.datePicker = [[UIDatePicker alloc] initWithFrame:CGRectZero];
-[self.datePicker setDatePickerMode:UIDatePickerModeDate];
-[self.datePicker addTarget:self action:@selector(onDatePickerValueChanged:) forControlEvents:UIControlEventValueChanged];
-
-Then link the datePicker to the textfield inputView:
-
-self.textField.inputView = self.pickerView;
-
--(void)onDatePickerValueChanged:(UIDatePicker *)datePicker
-{
-self.textField.text = [self.dateFormatter stringFromDate:datePicker.date];
-}
-  testing vivek
- testing vivek1
- testing vivek2
- testing vivek3
- testing vivek4
- testing vivek5
